export const BASE_URL = 'https://056b-31-143-51-22.ngrok.io/';
export const SETTINGS_ENDPOINT = 'api/v1/settings/';
export const SEARCH_ENDPOINT = 'api/v1/news/search/';
export const REGISTER_DEVICE_ENDPOINT = 'api/v1/settings/register_device/';
export const SELECT_SOURCE_TEXT = 'Kaynak Sec';
export const SELECT_SOURCE_PLACEHOLDER = 'Haber Kaynagi';
export const SELECT_CATEGORY_TEXT = 'Kategori Sec';
export const SELECT_CATEGORY_PLACEHOLDER = 'Kategori';
export const SEARCH_PLACEHOLDER = 'Ara';