# Generated by Django 3.1 on 2020-08-27 21:01

from django.db import migrations, models
import news.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('content', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('origin_url', models.URLField(max_length=500)),
                ('source', models.IntegerField(db_index=True, default=news.enums.NewsSource['lastnews'])),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
