# Generated by Django 3.1 on 2020-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.IntegerField(choices=[('general', 1), ('breaking_news', 2), ('economy', 3), ('sport', 4), ('agenda', 5), ('life', 6), ('world', 7), ('technology', 8), ('tourism', 9), ('cars', 10), ('health', 11), ('in_day', 12), ('art', 13), ('game', 14)], default=1),
        ),
    ]
