# Generated by Django 3.1 on 2020-08-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/500', max_length=500),
        ),
    ]
