# Generated by Django 3.1 on 2020-09-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200831_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(default='tr', max_length=3),
        ),
    ]
