# Generated by Django 3.1 on 2022-01-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200916_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
